package com.management_system.entity.enums;

public enum ITRole {
    FRONTEND_DEVELOPER,
    BACKEND_DEVELOPER,
    FULLSTACK_DEVELOPER,
    MOBILE_DEVELOPER,

    QA_ENGINEER,

    BUSINESS_ANALYST,
    PRODUCT_OWNER,
    PROJECT_MANAGER,
    SCRUM_MASTER,

    TECH_LEAD,
    SOLUTION_ARCHITECT
}
